### ISSUE TITLE
Design for Easy Stack resources

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#1096]
Easy stacks will install various resource classes and managed resources when an instance of their CRD is created, e.g. installing an "EasyGCP" stack might install a GKECluster resource class and the static network managed resources.

We need to figure out what exactly will be created by each cloud's stack, how the EasyFoo CR will allow the user to configure those things, etc.

**Comment by suskin** [comment]
There is slightly more to this as well: there is also the UI experience to consider.

Anyway, here are some random thoughts and links.

### Existing thinking

Here is an example of what we imagine [the experience for using a wordpress stack looking like](https://github.com/suskin/template-stack-experience/tree/master/wordpress-workload/quick-start) when we have template stacks, including installing a resource pack. Here's a link to the [imagined structure of a resource pack](https://github.com/suskin/template-stack-experience/tree/master/wordpress-workload/quick-start/resource-packs/dev/gcp). If possible, it'd be ideal if we could structure the source files of our resource packs in the same way, so that we can test our ideas and have something which is easy to convert to a true template stack.

I am also thinking that the controller side of this work will be a good place to experiment with logic that we may use in the controller side of template stacks.

### Open questions

There are some parts which are ambiguous, which we'll want to clarify as part of this process. It probably makes sense to try to clarify them early, because the clarifications will affect the user experience.

* How do users configure providers, especially the credentials?
* What would the flow of the UI look like, from installing the stack to applying the resources?

**Comment by muvaf** [comment]
> Here is an example of what we imagine the experience for using a wordpress stack looking like when we have template stacks, including installing a resource pack. Here's a link to the imagined structure of a resource pack.

I'd personally prefer a separation between resource classes and managed resources in the context of easy stacks. The reasoning is that managed resources may or may not refer to each other but the resource classes definitely refer to managed resources and in the context of _easy stacks_ resource classes are the top level resources that we expose to the user. It's a good peace of mind for someone who wants to fork the easy stack and make changes to know that he only needs to play with the managed resources folder.

In terms of controller side of the things, I imagine a top level folder will exist to host all possible YAML directories and controller will basically scan that top level folder recursively. So, it's just a preference in the end. I don't think folder structure will affect the execution logic.

> How do users configure providers, especially the credentials?

Since each easy stack will know what kind of `Provider` to use, I believe asking for a secret reference of the credentials in `spec` makes sense for this. For future scenarios where an easy stack configures a multi-cloud setup, the developer can include more than one field to its `spec` to get different secret reference for each cloud provider.

**Comment by prasek** [comment]
@muvaf @negz: I was talking with @infinitecompute today about the [GitLab 12.5 + Crossplane integration](https://docs.gitlab.com/ee/user/clusters/crossplane.html) where Crossplane adds managed PostgreSQL provisioning via standard GitLab pipelines and the [GitLab auto deploy app helm chart](https://gitlab.com/gitlab-org/charts/auto-deploy-app) using `postgresql.managed` and the `postgresql.managedClassSelector`.

We'd like enable use of Easy Stacks in the GitLab + Crossplane integration where:
 - GitLab provisions GKE or EKS clusters including associated networking
 - Crossplane is installed directly into an existing target cluster via the Crossplane helm chart using the `clusterStacks` field as show [here](https://github.com/crossplaneio/crossplane/blob/master/docs/install-crossplane.md#installing-cloud-provider-stacks).

Could the Easy Stacks CRD support a flag like `existingTargetCluster` that omitted the cluster class, network, subnet, etc. and also accepted an optional existing `network` ID as part of the Easy Stack CR, so it could populate the [classes and managed service access resources](https://docs.gitlab.com/ee/user/clusters/crossplane.html#configure-managed-service-access) needed for the GitLab integration? This would allow Easy Stacks to be used with the GitLab integration to simplify initial config for dev/test environments.

**Comment by muvaf** [comment]
> Could the Easy Stacks CRD support a flag like `existingTargetCluster` that omitted the cluster class, network, subnet, etc.

I don't think I understood this. Do you mean that you need an option in the easy stack that will deploy only database resource class and not others? 

> accepted an optional existing network ID as part of the Easy Stack CR, so it could populate the classes and managed service access resources needed for the GitLab integration

Sure, we can do that.

**Comment by prasek** [comment]
@muvaf yes, only the resources classes for db, cache, buckets, etc. it's unclear when we'll need this though, so let's handle this scenario separately from this design. Thanks.

**Comment by muvaf** [comment]
Fixed by https://github.com/crossplaneio/crossplane/pull/1103 and https://github.com/crossplaneio/crossplane/pull/1110
