### ISSUE TITLE
template stacks: Unpacking should create a TemplateStack object instead of Stack if it's a template stack

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#1210]
### What problem are you facing?

Currently, stack manager unpacking process creates all CRDs and `Stack` object. What we do in template stacks is that we reconcile a `TemplateStack` object and generate a `Stack` object accordingly.

### How could Crossplane help solve your problem?

We need unpacking process to see that the stack source is a template stack and only create the TemplateStack CR. How it works today is that `config/stack/app.yaml` and `config/stack/install.yaml` is merged to create a `Stack` object with additional information from CRDs.

What we need is that we can have a file that defines the `Behaviors` of `TemplateStack` and instead of `Stack`, we should generate a `TemplateStack` object. As an initial step, we can have a file called `behaviors.yaml` to define `TemplateStack.spec.behaviors` object and treat the stack as template stack if that file exists and do the necessary operations.

The structure of `TemplateStack` is pretty similar to `Stack` [with a few changes](https://github.com/crossplaneio/crossplane/issues/1209) but I believe it should be possible to use some of the existing mechanisms that creates `Stack` objects using those files in the bundle.

There is also an [issue](https://github.com/crossplaneio/crossplane/issues/1178) merging `app.yaml` and `install.yaml` into one `stack.yaml` that lives in the root of the directory. However, how that `stack.yaml` will look like is not certain yet. So, I'd go with what we have today to implement this issue.

**Comment by displague** [comment]
After some discussion with @muvaf and @suskin, a template stack will be expected to contain only a `stack.yaml`.  This `stack.yaml` will contain all of the fields expected in `app.yaml` along with the ones currently provided by `stack.yaml` (which today has template stack features, including behaviors defined).

Eventually, the Stack Manager will only look for `stack.yaml`, which does not need to contain template stack features.

**Comment by suskin** [comment]
I was thinking about this a little more, and I'm wondering whether we can treat the "`TemplateStack`" kind as the thing the user writes in their `stack.yaml`, but underneath it's all folded into a `Stack` object by the time the stack manager creates an object. So the only object created in the cluster is the `Stack` object. Since the intended TemplateStack is a superset of a Stack, it seems like it should work out pretty well.

**Comment by jbw976** [comment]
I was wondering something similar @suskin, I am hoping that we don't end up with a new Kind defined that people have to learn, understand, and make choices around if they need that Kind or another one of the Stack kinds.  My inclination is to end up with less Kinds not more to simplify things.

**Comment by displague** [comment]
Some conversation, and the existing `StackConfiguration` resource are defined as the full body CR of a `StackConfiguration` CRD.

I've been leaning in the opposite direction, going along with the pattern set by `app.yaml`, which would suggest that `behaviors.yaml` (or `stack.yaml` as a combination of `app.yaml` and `behaviors.yaml`) would omit the outer layer (APIVersion, Kind, Metadata, Spec, Status) and would only contain the yaml equivalent of the Spec contents.

**Comment by displague** [comment]
Stacks aren't entirely consistent about this however, because stacks use a full bodied Deployment CR in the `install.yaml`.

**Comment by suskin** [comment]
@jbw976 after some more conversation, we are thinking that the `StackDefinition` in a `stack.yaml` is a replacement for the information in `app.yaml`, which means it's a single Kind and is the only Kind that stack authors interact with; it accommodates all the flavors of stack. Underneath we're planning on copying it over into a `Stack` in the cluster for now, but that's hidden to the user and is an implementation detail that we expect to change in the future.

**Comment by displague** [comment]
The current Stack manifest file defining template stack behaviors, `stack.yaml`, is a `StackConfiguration` CR.

The Stack manifest also contains `app.yaml` which is a subset of the Stack CR `spec`.

As we move towards a `StackDefinition` CR (#1214), we could have a smoother transition path by using the name `behavior.yaml` to represent the behaviors part of the StackDefinition CR, rather than `stack.yaml`.  

A `stack.yaml` that represents a StackDefinition CR populated with only the Behavior subset, working in conjunction with the existing `app.yaml`, is confusing.

The future `stack.yaml`, in our current thinking, will  be a StackDefinition CR.  I intend to implement this now by populating a StackDefinition with app.yaml (Spec) and behaviors.yaml (Spec.Behaviors).

A `behaviors.yaml` file can be introduced without a change to the ecosystem.  Changes to `stack.yaml` do affect the ecosystem, albeit a very tiny piece.  We can defer these changes until later.

`/stack.yaml` is valuable real-estate.

It is possible that the future `stack.yaml` will look very different (based on the intentions of the StackDefinition gist) and the structure offered in the Stack + StackInstall merge issue.  Should we be (re)defining that file now only to revisit a complete rewrite of that file again later?

With this reasoning, I intend to consume a `behaviors.yaml` file, keeping the existing `stack.yaml` treatment in place.

In the presence of a `behaviors.yaml` file, the `stack unpack` command will combine `app.yaml` and `behaviors.yaml` into a StackDefinition (per #1214)  and emit this StackDefinition.  A `Stack` will not be emitted by Unpack in this situation, being deferred to the controller watching StackDefinition resources.  This controller will be in a better position to emit a Stack resource since it may be dynamically producing Stack CRDs.

An alternate approach where `stack unpack` produces both the Stack and StackDefinition (or StackConfiguration or StackBehaviors), while a separate controller watches the StackDefinition files, observes a ref relationship between the two, and patches the related Stack resource was considered but not the approach ultimately chosen.

**Comment by suskin** [comment]
@displague and I discussed the `behaviors.yaml` versus `stack.yaml` options a bit more in Slack; summarizing the outcome here.

We both agree that the next state will be a temporary state as we consolidate the behavior configuration and the stack app metadata, and the stack configuration. We're trying to get the best combination of something we can iterate on quickly, and something which has minimal disruption for our users (which is not high in this case, but which we want to build a habit of considering as a factor).

We also agree there is no single right way, and both `behaviors.yaml` and `stack.yaml` work. And, we want the person who is working in the area to be able to make the decision quickly based on their best judgment, without having to wait for approval.

Marques's reasoning and plan sound solid to me. Even though I was pulling for the `stack.yaml` approach during the debate phase, I fully support Marques's plan now that he's made a decision and we are moving to the action phase.
