### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#137]
Redis is offered as a managed service in most cloud providers:

* AWS: https://aws.amazon.com/redis/
* GCP: https://cloud.google.com/memorystore/
* Azure: https://azure.microsoft.com/en-us/services/cache/ (edited)

We should add support for Redis, including dynamic provisioning.

**Comment by negz** [comment]
I'm going to take a pass at this. I imagine my first deliverable will be a PR proposing API templates - at this stage I'm thinking about creating a new `cache/v1alpha1` API group, but this could also arguably fit under `storage/v1alpha1`. Once we've settled on an initial API I'll work on implementing this for GCP, since I'm most familiar with that cloud.
