### ISSUE TITLE
Decrease the number of updates from Reconcile loops

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#209]
@ichekrygin brings up a good point in https://github.com/crossplaneio/crossplane/issues/208, and I think I agree now too that we can potentially call `Update` less frequently from our controllers.

Copied here for readability:

General feedback: the more I think about calling r.Update multiple times after every property change in the routine, vs. calling it a single time - the more I think the latter is arguably a "better" approach.

For me it boils down to the following:

* calling it a single time is more efficient (less updates calls to API, less object reconcile batching in controller-runtime)
* calling it a single time is more straight forward in terms of error handing branching logic.

There is a perception that if we set an object property and don't follow by the immediate update, there is a chance that changes could be lost. While in theory, there is a chance of that, in practice all our reconcile events end with r.Update for one reason or another (r.fail(...) - will persist all the object's property changes).

**Comment by jbw976** [comment]
For this issue, we should evaluate all the places we are calling Update in the middle of a Reconcile instead of returning from a Reconcile.

We should remove cases where we are calling update in the middle of Reconcile.

**Comment by negz** [comment]
I believe our current controllers update managed resources the minimum reasonable amount of times. This is not necessarily once per reconcile, since sometimes we want to decouple the logical steps of reconciling a resource (adding a finalizer, updating bindings, late initializing spec fields, updating status, etc) into separate pluggable logic. We'd need some significant re-architecture of our reconcile logic to get down to one update per reconcile - I don't think this is worthwhile in order to reduce load on the API server.
