### ISSUE TITLE
Use Status SubResource for Crossplane Types

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#298]
Feature Request - Improvement

Currently, `Crossplane` does not use (properly) Status SubResource as described in the [kubebuilder Quick Start](https://book.kubebuilder.io/basics/status_subresource.html).

Add annotation to the type
```go
// MySQL is the Schema for the mysqls API
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
type MySQL struct {
    metav1.TypeMeta   `json:",inline"`
    metav1.ObjectMeta `json:"metadata,omitempty"`

    Spec   MySQLSpec   `json:"spec,omitempty"`
    Status MySQLStatus `json:"status,omitempty"`
}
```

Switch to use `Status().Update`
```go
    instance.Status.SomeField = "new-value"
    err = r.Status().Update(context.Background(), instance)
```
instead of full instance update
```go
    instance.Status.SomeField = "new-value"
    err = r.Update(context.Background(), instance)
```

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane/blob/bc91669/pkg/apis/compute/v1alpha1/types.go#L155

FYI, we do have this enabled on Workload (only) at the time of writing. I was racking my brain as to why I couldn't update Workload status using the same pattern as other controllers when when I remembered this issue and decided to doublecheck. :)

**Comment by negz** [comment]
Another musing after a quick attempt to use this pattern. Often when we're reconciling we want to add or remove finalizers. Finalizers live in metadata, not the status, so if we switch to this pattern we'll likely need to update both the status and the object itself.

**Comment by jbw976** [comment]
Another thing to consider, and I don't have proof of this right now (it is just from memory), that when you enable the Status subresource with:
```
// +kubebuilder:subresource:status
```
You **seem** lose the ability to update the status along with the full instance update.  i.e. if you just want to update a status field and then call `r.Update(ctx, instance)`, the update to the status won't get committed to the API server.

We should verify this, but it's definitely something to watch out for and be careful with.

**Comment by negz** [comment]
@jbw976 I noticed this and left a comment on @ichekrygin's forthcoming reconciler patterns design doc.

API wise, I prefer calling Update on the entire resource rather than on its status subresource. This way my controller logic is "if I changed this resource I must call Update". When using the status subresource I must include logic to track which part of the resource I updated and call the appropriate Update function(s).

I wish https://book.kubebuilder.io/basics/status_subresource.html was more explicit about _why_ generating code using `// +kubebuilder:subresource:status` is preferred (or whether it is preferred at all?). It quotes the following from the [Kubernetes API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status):

> The PUT and POST verbs on objects MUST ignore the "status" values, to avoid accidentally overwriting the status in read-modify-write scenarios. A /status subresource MUST be provided to enable system components to update statuses of resources they manage.

So my best guess is that CRDs that do not use `// +kubebuilder:subresource:status` are not compliant with the current iteration of the Kubernetes API conventions?

**Comment by ichekrygin** [comment]
> So my best guess is that CRDs that do not use // +kubebuilder:subresource:status are not compliant with the current iteration of the Kubernetes API conventions?

This is my guess as well. I am also under the impression (not verified), that when we use `status` subresource, the external Update (`kubectl apply/create`) will (or should) ignore `status` structure and update only `spec`.

**Comment by jbw976** [comment]
I got bit by https://github.com/crossplaneio/crossplane/issues/298#issuecomment-476452772 myself just now.  It took me awhile to realize why my finalizer wasn't getting set on objects I was reconciling.  The reason was because after setting the finalizer on the object in memory, i was calling `Status().Update` which as @negz pointed out doesn't update the finalizers because they live in object metadata not in status.

this seemed to work OK:
```golang
if !util.HasFinalizer(&(h.i.ObjectMeta), extensionFinalizer) {
    util.AddFinalizer(&(h.i.ObjectMeta), extensionFinalizer)
    return requeueOnSuccess, h.kube.Update(ctx, h.i) // full object update since finalizer is stored in object metadata
}
```

This `Status().Update` pattern continues to be easy to use improperly, or to get unintentionally bitten by its consequences 🤕

**Comment by negz** [comment]
Per discussion in this issue it's not super clear whether this is a bug, enhancement, or something else, so I've added `techdebt` and `design`.

**Comment by displague** [comment]
@negz can this be closed now that we are committed to using crossplane-runtime's reconciler in the stacks we manage?

**Comment by negz** [comment]
@displague I think so. In practice some older managed resource controllers don't use the status subresource, but all claims and all managed resources that use the crossplane-runtime managed resource reconciler do. This will resolve itself as we port all managed resources over to crossplane-runtime.
