### ISSUE TITLE
Convert pkg/controller/gcp/database to new Controller structure/test paradigm

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#299]
### Overview
This issue is a subset of #269

**Comment by negz** [comment]
@ichekrygin Is it the GCP package we want to convert, or the Azure one? I thought GCP was the reference "good" implementation?

**Comment by jbw976** [comment]
@negz this issue is just for the database package of GCP.  The other packages in GCP are OK but the database one needs conversion/updating.

Most (all) of the Azure packages also need updating. 

The key to look for is if the controller has member fields that are functions and can be set directly for unit testing purposes, e.g., https://github.com/crossplaneio/crossplane/blob/release-0.1/pkg/controller/gcp/compute/gke.go#L75-L78

If a controller has that, then it is following the agreed upon paradigm.

**Comment by HashedDan** [comment]
I believe the Resource Groups for Azure will serve as a good example of what converting over the other Azure resources will look like. They are modeled after the GKE controller. @negz feel free to take a look here until merged: https://github.com/HashedDan/crossplane/blob/azure_resource_groups/pkg/controller/azure/provider/resourcegroup.go

**Comment by negz** [comment]
@ichekrygin Do you think it's worth keeping this issue open? I believe at this stage many of our controllers need refactoring, so I'm not sure it's worth having an issue for this specific one.

**Comment by displague** [comment]
@negz is there a parent issue for that encompassing refactor? This issue could become a bullet of the parent and we could create more vite-size issues (per controller needing refactoring).  These may be good first issues once the pattern is established.

**Comment by ichekrygin** [comment]
@negz I let you decide. I don't mind either way.

**Comment by jbw976** [comment]
it looks like #269 is the umbrella issue and some related tasks to accomplish that overall vision are being linked there.  I think we should be tracking all of this work at the task level not at the code area level.  So I think we can close this one that is specific to one part of the code area.
