### ISSUE TITLE
Support for Single Kubernetes Cluster Mode

### ISSUE THREAD

**Issue by bassam** [crossplaneio/crossplane#352]
* Feature Request

**What should the feature do:**
Crossplane defines the concept of a workload and resources today. Today, a workload is a schedulable unit that includes a payload (config YAML) that can be deployed to a target Kubernetes cluster. This model enables deployments across different clusters, and clouds.

However, if your goal is use a single Kubernetes cluster only this model gets in the way. We should consider supporting a single cluster mode for Crossplane. In this mode we do very little with workloads and scheduling of workloads, and instead focus only on resource claims, classes and their associated controllers.

If we consider the Gitlab scenario in a single cluster mode, they could run their helm chart as is against a Kubernetes cluster, and use the Postgres, Redis and other APIs provided by crossplane without having to do anything with workloads.

**What is use case behind this feature:**
Customers that want to run crossplane on a single Kubernetes cluster.

**Comment by negz** [comment]
@bassam In recent discussions around supporting Gitlab we mentioned updating the Gitlab Helm chart to generate Crossplane workloads and resources. I wonder if we could maintain that same pattern in the proposed single cluster mode by adding a resource that satisfies the `KubernetesCluster` resource claim with a reference to the cluster upon which Crossplane is running (rather than by spinning up a hosted Kubernetes cluster)?

**Comment by bassam** [comment]
Yeah a short-circuited `KubernetesCluster` could work, however it still requires wrapping YAML in a `workload`. I was thinking about a mode where I don't want to use the workload scheduling features of crossplane, just the resource abstraction/controllers.

**Comment by negz** [comment]
On rereading this issue, I feel like this is a pretty common use case that we support today. I'm going to close this - let me know if I'm missing something.
