### ISSUE TITLE
v0.2 - Unable to create a GCP sql instance

### ISSUE THREAD

**Issue by WTFKr0** [crossplaneio/crossplane#508]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The process of creating the gcp sql instance is OK but crossplane can't set the user password

**How to reproduce it (minimal and precise):**
Just create a gcp sql instance with version `crossplane/crossplane:v0.2.0`

The error is : 
`failed to start update user operation for user 'root': googleapi: Error 400: Invalid request: Invalid host in request body.`
I found a related issue on gcp golang lib : https://github.com/googleapis/google-api-go-client/issues/364#issuecomment-498600085

**Comment by teddyking** [comment]
I've also run into this as well. There's been some discussion about it in the slack channel ([link](https://crossplane.slack.com/archives/CEG3T90A1/p1559315060008000)).

**Comment by jbw976** [comment]
@WTFKr0 found a potential workaround for this issue here: https://github.com/wozniakjan/google-api-go-client/commit/26a5f74bf4855c6095a0a0da07a2539aea5458bf.  Thanks for sharing that find!

I'm hoping that this gets fixed upstream and we don't have to fork the google-api-go-client, we should look further into this.
