### ISSUE TITLE
Integration level testing

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#528]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** As part of our continuous integration process, we should also be running tests at the integration level.  We currently run a suite of unit tests, but we don't run and test Crossplane at a higher level that is more representative of real world usage.  We should deploy Crossplane into a Kubernetes environment and run a suite of tests that verify functionality of the fully integrated code.

**What is use case behind this feature:** Integration testing can catch issues and regressions that are not caught when testing isolated portions of the code base in unit tests.  It is more representative of real world usage and is very valuable to maintaining code quality.

**Comment by negz** [comment]
We've run into a few cases lately in which integration tests would have been handy, for example programmer errors in which I've forgotten to register certain controllers with the controller manager.

Our codebase is entering a state of flux at the moment so integration tests are a bit of a moving target, but some basic MVP scaffold that just ensures Crossplane can start would be a good first step to build from. @soorena776 is interested in taking this as a first issue to get to know Crossplane a little better.

**Comment by hasheddan** [comment]
Thanks so much @soorena776, this will be a big improvement!

**Comment by suskin** [comment]
I am not sure whether this is the right issue for this request, but it would also be great if we could make it easier to validate that the end-to-end examples work when we make changes. It seems that the current state is that the examples could be broken and we wouldn't know until someone runs one by hand and [reports it](https://github.com/crossplaneio/crossplane/issues/519).

Ideally the end-to-end tests would be automated and would run with every pull request, but if that is too challenging, adding a way to do it locally with a single command would also be good, so that developers can validate locally.

**Comment by displague** [comment]
@suskin I agree with some caveats.


> Ideally the end-to-end tests would be automated and would run with every pull request

We would want gates on this - core team approval per pull request.  Some pull-requests may not require builds on obviously unrelated providers.  This becomes easier when each provider lives in its own repository and is isolated from changes in other providers.  We may want to have core project changes trigger builds on the dependent projects, depending on how isolated those projects are from upstream changes (do they opt-in to crossplaneio/crossplane via versioning).


> It seems that the current state is that the examples could be broken and we wouldn't know until someone runs one by hand and reports it.

While this is sensible for the core team, most contributors will not have credentials for more than one or two of the effected providers.  A CI/CD pipeline that triggers cloud builds makes this experience more accessible.  Here's an example of how https://github.com/kubermatic/machine-controller allows users to interact with the build process in this way:
https://github.com/kubermatic/machine-controller/pull/451#issuecomment-466790459

In local development, when you have the provider credentials in place, testing changes involves:

```sh
make
cluster/local/minikube.sh update
cluster/local/minikube.sh helm-update
cluster/local/minikube.sh restart
kubectl apply -f cluster/examples/workloads/kubernetes/wordpress-gcp/cluster.yaml
kubectl apply -f cluster/examples/workloads/kubernetes/wordpress-gcp/app.yaml
... observe
kubectl delete -f cluster/examples/workloads/kubernetes/wordpress-gcp/app.yaml
```

@negz pointed out in an earlier PR that moving `provider.yaml` to `cluster/examples` root would make this easier because documentation for the examples could refer to a single document that configures the provider credential, and each example directory could take advantage of `kubectl apply -Rf` and `kubectl delete -Rf`.

**Comment by jbw976** [comment]
I met with @soorena776 today to discuss some starting points and potential extreme scoping of this effort to get it off the ground with a reasonable minimal effort.  A good starting point will be to take a black box approach where we simply bring up a minimal local cluster and deploy the built Crossplane artifacts into this cluster, verifying that the controllers come up, are not crash looping, and have an OK status.  We do not yet need to worry about testing cloud provider resources, this will initially just serve as a sanity smoke test to make sure we haven't completely borked the Crossplane installation.

The Rook project built an integration testing effort that I wanted to provide some pointers to in this write-up to serve as references.  We should not repeat everything Rook did, but it does provide a good starting point for our efforts.

First, there’s a lot of similarity between the build systems of Rook and Crossplane.  Rook’s grew organically over a couple years, and Crossplane’s was taking all those lessons learned and putting them into a reusable build repo: https://github.com/upbound/build/.  So you’ll see some things in Rook that may look familiar to what you see in Crossplane, but maybe not as refined :)

The Rook CI system is hosted at https://jenkins.rook.io/.  The main pipeline that drives everything can be seen at the root of the Rook repo here: https://github.com/rook/rook/blob/release-1.0/Jenkinsfile

The basic flow is that the CI build/test pipeline will be kicked off on Jenkins automatically for each pull request and for each commit to master.  Here’s a recent example of a successful CI run for a pull request: https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-3520/2/pipeline

The main stages for each CI run are:
* Build - compile binaries, build images, docs, and helm charts
* Unit tests - run all developer unit tests essentially with “go test”
* Integration tests - run the suite of integration level tests on multiple versions of Kubernetes
* Publish - upload/publish all artifacts to their hosted locations (dockerhub, helm chart repo, etc.)

We already have something similar defined in Crossplane in its [Jenkinsfile](https://github.com/crossplaneio/crossplane/blob/master/Jenkinsfile), so this would be a great place to add a new stage for Integration Tests.

As shown in Rook’s [Integration Tests stage](https://github.com/rook/rook/blob/release-1.0/Jenkinsfile#L78-L112), it is calling the `RunIntegrationTest` function for each version of Kubernetes that we have in our current matrix.  That function essentially does 2 main steps:

1. Brings up a Kubernetes cluster at the desired version in the desired cloud provider using kubeadm: https://github.com/rook/rook/blob/release-1.0/tests/scripts/kubeadm.sh
    1. We used to do AWS and GCP, but we only do AWS now since we had reliability problems with GCP
1. Execute integration tests binary containing Go code tests that programmatically deploy the Rook operators and exercise their functionality by talking to the Kubernetes API

More details about these scripts and the integration test binary can be found in the README: https://github.com/rook/rook/blob/release-1.0/tests/README.md

The test framework and the specific test cases can all be found under the tests dir:
* Framework: https://github.com/rook/rook/tree/release-1.0/tests/framework
* Test cases: https://github.com/rook/rook/tree/release-1.0/tests/integration

This model has worked well for some things, but I’m thinking we can simplify a lot of this for our first step at getting Crossplane integration testing off the ground.  One major simplifying assumption for now is that Crossplane should use a lightweight local cluster (KinD?), we should not bring up a full cluster using cloud provider resources (yet at least).

I think there are also some bad practices in the Rook tests that we’d want to avoid, such as duplicating YAML to install controllers and types in the examples, the helm charts, AND the integration tests themselves.  I’m hoping we can take a black box approach and simply reuse the Crossplane artifacts from the build stage.  Not sure how best we could reuse the resources from the Helm chart (deployment, role bindings, etc.), but it seems like it would be wise to reuse and test those too so we are exercising the same things we will be expecting our users too, hopefully finding issues before they do.

Hope this helps as a starting point, let me know if you have any questions.
