### ISSUE TITLE
Consider versioning Crossplane controllers

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#533]
Crossplane resources follow Kubernetes conventions, existing within a versioned API group, for example `compute.crossplane.io/v1alpha1`. Our Go resource type definitions model this in their directory structure, which is is nested as roughly `pkg/apis/group/version`, e.g. `pkg/apis/compute/v1alpha1`.

Each Crossplane controller operates on a specific version of a resource, but the controller implementations themselves are not versioned. The controller directory structure is (very) roughly `pkg/controller/group/kind`. This works for the moment because we only have one version (`v1alpha1`) of each resource kind.

Once we need to avoid breaking changes to API definitions we'll either need one controller per version of each kind, or some way to translate older resource versions to newer ones before passing them to the relevant controller. e.g. Build a controller that supports only `foo.crossplane.io/v1beta1`, and translate any `foo.crossplane.io/v1alpha1` instances to `foo.crossplane.io/v1beta1` before passing them to said controller.

**Comment by hasheddan** [comment]
So if we look at a controller for something like AWS EKS, it [consumes](https://github.com/crossplaneio/crossplane/blob/9418ed64b2a4cd7f95b9d4096f6df99c4bbd3ee3/pkg/controller/aws/compute/eks.go#L134) an actual instance of the `v1alpha1` version of the EKS resource type. If we update / build a new controller for AWS EKS that consumes a `v1beta1` version, do we want to have a mechanism built-in to perform a sort of "hand off" from one controller to the other, or would the user just be running some `v1alpha1` EKS clusters and the onus is on them to slowly migrate? (i.e. on next deployment of each EKS cluster switch to `v1beta1`)

My initial thought it probably just build a new controller like you said and allow for slow migration. However, because Crossplane resources are a sort of abstraction on the underlying resources of a specific cloud provider, the actual deprecation of old resource versions is not always under our control. (i.e. if AWS decided that EKS was fundamentally changing and in 1 year the existing method for running a cluster may no longer be supported, then it also would not be supported on Crossplane)

Another consideration is what if a provider's API was updated, but the underlying resource stayed the same? Would we just update the controller but keep the resource version the same? I guess it boils down to *is there a 1-to-1 mapping between controller version and resource version*?

**Comment by negz** [comment]
I'm not sure if this issue still makes sense - I think it might be based on a flawed understanding of how CRDs work. I think the general idea is that you write controllers for one version of a CR, then add translation webhooks to translate any other version to the one supported version? 🤔

**Comment by muvaf** [comment]
> I think the general idea is that you write controllers for one version of a CR, then add translation webhooks to translate any other version to the one supported version?

That is my understanding, too. @hasheddan tried to do it for GKE v1beta1 and that was his conclusion as far as I remember.

**Comment by hasheddan** [comment]
@muvaf @negz yep to have multiple versions of a CRD present in a cluster, there needs to be a stored version which is the hub that all other versions must be "round-trippable" through. Conversion must preserve all information in both directions, which is usually not the case for most of our upgrades.

**Comment by negz** [comment]
Thanks guys - given this issue doesn't really make sense I'm going to close it out.
