### ISSUE TITLE
Azure: Update examples and README files containing Wordpress examples

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#650]
Update `cluster/examples` and `docs/` with portable Wordpress on Azure.

Part of #617
Depends on #572, #647, #648, #649 
### What seems to be the problem?

Examples and documentation do not exist for deploying the portable Wordpress application stack [#572] on Azure.

### What could Crossplane do to help?

Examples and documentation should be updated to contain necessary `YAML` files and directions for deploying the portable Wordpress application stack on Azure.

### What does it look like when we're done?
A user can:

* Find all resource classes, network resources, and defaulting policies needed to allow the portable Wordpress stack to be provisioned on Azure.
* Find documentation with instructions on how to setup Azure and install the Wordpress app stack.

### Todo
- [ ] Azure portable Wordpress examples created.
- [ ] Azure portable Wordpress docs created.

**Comment by displague** [comment]
I had problems with my Azure account and left this PR behind.  It may be a starting point for this work.
https://github.com/crossplaneio/crossplane/pull/574

**Comment by hasheddan** [comment]
Awesome, thanks @displague!

**Comment by displague** [comment]
The issue would be a parent to https://github.com/crossplaneio/crossplane/issues/538 and would close https://github.com/crossplaneio/crossplane/issues/519 (so long as the GCP and AWS examples and docs haven't drifted away).

**Comment by jbw976** [comment]
There may be some work in #574 that we could reuse for the Azure docs update, but potentially not if our docs overhaul for v0.3 is fairly drastic.

**Comment by jbw976** [comment]
We have documentation for installing Wordpress in Azure via the services guide and the stacks guide:
* https://crossplane.io/docs/v0.3/services/azure-services-guide.html
* https://crossplane.io/docs/v0.3/stacks-guide-azure.html

Users should be able to copy and paste from those guides to end up with WordPress running in Azure.

So I think what's still missing from this issue is the `cluster/examples` yaml files, which we have for GCP and AWS, but not for Azure:
https://github.com/crossplaneio/crossplane/tree/master/cluster/examples/workloads/kubernetes/wordpress

**Comment by hasheddan** [comment]
@jbw976 I should be able to get this done and close out the issue today!
