### ISSUE TITLE
Stacks CLI commands to install and uninstall a stack

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#720]
Related to #614 

### What seems to be the problem?

As part of working on #614, I would like to easily install a stack within the same CLI experience.

### What could Crossplane do to help?

Provide a CLI utility I can use to install a Stack, for example:
```
kubectl crossplane stacks install myorg/mystack
kubectl crossplane stacks uninstall myorg/mystack
```

Underneath, the `kubectl` plugin implementations would simply populate and create a `StackRequest` object for the user provided stack name, maybe directly with `kubectl`.

### What does this look like when it's done?
* kubectl plugin command to install and uninstall a Stack
* docs & examples

**Comment by suskin** [comment]
I am working on this in a [personal repo](https://github.com/suskin/crossplane-stack-cli) for now.

**Comment by suskin** [comment]
I have the first implementation here: https://github.com/crossplaneio/crossplane-cli/pull/2

I'm not **100%** happy with the syntax yet, but I think it's close enough for the level of polish that we're going for in the 0.3 release.

More specifically, there are some questions we'll want to keep thinking about regarding the following:
* Passthrough of other kubectl arguments
* The naming for the stack for install vs uninstall (right now they're different, because install uses image name and uninstall uses stack resource name)

**Comment by suskin** [comment]
I have closed this since the first implementation is merged now. There is some light documentation about the commands. We may want to improve the documentation in the future, but we can track that in a separate issue.
