### ISSUE TITLE
Template Stacks should be reconciled through some controller

### ISSUE THREAD

**Issue by displague** [crossplaneio/crossplane#878]
### What problem are you facing?

Following the Design for Template Stacks [#877], an implementation of this design will be necessary.

### How could Crossplane help solve your problem?

Per #877, the Crossplane Stack Manager will need to the following changes:
* Template Stacks design (especially Stack examples) should be updated to correspond with experience thinking in #891 (https://github.com/suskin/template-stack-experience/)
* Stacks design (especially filesystem layout) will need to be updated to correspond with #891 (https://github.com/suskin/template-stack-experience/)
* Stack Manager (Unpack) will need to be updated to consume template files and apply them to the Stack record
* Stack Manager (Manage) will need to create a Template Stack Manager Deployment for each Template Stack #955
* **Template** Stack Manager will need to reconcile CRs using template definitions found in the Stack #955

**Comment by suskin** [comment]
Just want to make a note that the current filesystem layout for template stacks is intended to use the same basic folder hierarchy as the existing stacks format. Some of the levels of hierarchy have been left out since they seemed unnecessary for the examples, but it is assumed that they will still exist in Real Applications.

**Comment by jbw976** [comment]
This was included in the template stacks preview in 0.7
