### ISSUE TITLE
UI-Schema Status Spec

### ISSUE THREAD

**Issue by rathpc** [crossplaneio/crossplane#929]
As of right now there is no defined spec to be able to drive status information for a given stack or resource from a GUI perspective. It would be useful to add keys to the existing `ui-schema.yaml` file that can be used for this purpose.

We can leverage the types from the array of `conditions` within the `conditionedStatus` key defined in status.

**Comment by jbw976** [comment]
The design for this has been merged to master in #930.  The design 1-pager can be found at https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stack-status-spec.md.

@displague or @suskin, I'm hoping to include this in v0.4 so consumers of Crossplane can start using it after that release.  I **think** the Stack Manager doesn't actually have to be updated though to deal with these new fields because the `ui-schema.yaml` files are completely opaque to the SM.

Perhaps reasonable support here would be to update some of the existing stacks to include `ui-schema.yaml` files for their CRDs, and define some `resourceConditionPaths` for them? Let's follow-up with @rathpc to clarify.

**Comment by displague** [comment]
@jbw976 https://github.com/crossplaneio/sample-stack/pull/4 Is ready to go

Since this is a 2 line PR, we can easily create this for the other Stacks.

In a conversation with @rathpc earlier, he pointed out that UIs could fallback to the CRD `printcolumn` defined conditioned status, so this may not be necessary.

**Comment by displague** [comment]
I've created the following PRs on the GCP, Azure, and AWS Stacks to provide the base ui-schema.yaml (#751) for those stack CRD files and to define that the resources in these stack should take advantage of the Crossplane Runtime "Ready" conditioned status:

* https://github.com/crossplaneio/stack-aws/pull/50
* https://github.com/crossplaneio/stack-azure/pull/42
* https://github.com/crossplaneio/stack-gcp/pull/63

/CC @rathpc @jbw976 @suskin @turkenh @thephred

**Comment by jbw976** [comment]
All of @displague PRs have been merged into their respective master branches and should be included in the v0.4 release timeline.
