### ISSUE TITLE
Support "side effects" during dynamic provisioning

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#968]
### What problem are you facing?

We're increasingly encountering scenarios in Crossplane in which more than one managed resource would need to be dynamically provisioned in order for a resource claim to result in a useful managed resource. Examples include:

* Azure SQL Server virtual network rules. These are firewall rules that whitelist a particular Azure subnet to connect to an Azure SQL server. They must be created _after_ the managed resource is created, because the rule states what managed resource it applies to.
* GKE cluster node pools. The GKE API supports modelling node pools either in-line in the GKE cluster object, or as distinct managed resources. Crossplane prefers the latter approach for its managed resource representations (citation needed) - e.g. modelling distinct `kind: GKENodePool` managed resources rather than one huge `kind: GKECluster` managed resource. However, a `KubernetesCluster` claim author probably wants some node pools for their cluster, rather than a control plane alone.

### How could Crossplane help solve your problem?

This will be a little vague, but one approach here may be to support "side effect classes" during dynamic provisioning. e.g. If a `MySQLInstance` claim lands on an Azure `MysqlServerClass`, that class can specify other resource classes that should be used for side effects. One of these classes would be a `MySqlServerVirtualNetworkRuleClass` used to create a `MySqlServerVirtualNetworkRule` for the dynamically provisioned `MySqlServer`.

**Comment by soorena776** [comment]
A few thoughts:

>  Crossplane prefers the latter approach for its managed resource representations (citation needed)

It's not clear to me why this is a preference. Crossplane is already using such complex managed resources in several places (EKSCluster, RouteTable, InternetGateway). Perhaps the preference is rooted in the fact that we want to have high fidelity with regards to the external cloud resources. In that case, I don't think grouping most related resources together as a bigger and complex resource prevents us from maintaining high fidelity, rather it could result in a superset of external cloud resources. 

The other reason that I am guessing is creating this sense of preference, is the fear that combining multiple resources together to create a bigger and more complex resource might become unwieldy soon. 

This definitely will be the case if we put independent and unrelated resources together and make a complex resource. For instance, we could combine a VPC with an RDS instance and call it a VPCWithRDS resource. Such resource is useless as its functionality can easily be expressed in YAML file level, and it also is hard to maintain. 

However in a lot of scenarios the resource `A` and its side-effect `B` are so entangled together that combining them together makes a lot of sense. For one, `B` is always, or almost always is used with `A`. Additionally, combining the resources will prevent from surfacing the low level connection information all the way up to the API, in order to connect them in YAML. AWS RouteTable  and Route and Association side effects are a good example for such scenario:
https://github.com/crossplaneio/stack-aws/blob/master/pkg/controller/network/routetable/controller.go#L157

The other issue that I am having with the claim based proposal above is that it's not readily clear to me how `MySqlServerVirtualNetworkRuleClass` is better than just a complex resource, as both are creating a K8S type that is involved with multiple resources types. Even the claim based approach requires designing a new algorithm and new implementation to support side-effects in the existing resource classes.

In a spectrum of using no complex resources in one end, and using arbitrary complex resources in the the other end, I would suggest we land in between; avoiding unnecessary complex resources, and creating complex resources where it seems reasonable.

Related: https://crossplane.slack.com/archives/CKXQHM7U3/p1571975417029600, and the following comments


/CC @hasheddan @negz

**Comment by negz** [comment]
@soorena776 I think there's (at least) two similar but not identical scenarios here:

1. External resources that model concepts as both distinct and combined API objects. GKE is an example of this; it allows you to manage node pools either inline of the Cluster API object, or as a distinct NodePool API object.
1. Tightly coupled external resources that can only be modelled as distinct API objects. Azure SQL is an example of this. Virtual network rules are always a distinct API object (from SQL servers) in the Azure API, but are only useful when applied to an SQL server.

It seems like your concerns mostly relate to case 2.

> Crossplane is already using such complex managed resources in several places (EKSCluster, RouteTable, InternetGateway).

I don't think the fact that we're in some cases doing it this way already has much bearing on whether it's a sensible design.

> Perhaps the preference is rooted in the fact that we want to have high fidelity with regards to the external cloud resources. In that case, I don't think grouping most related resources together as a bigger and complex resource prevents us from maintaining high fidelity, rather it could result in a superset of external cloud resources.

One aspect, in my mind, of fidelity is granularity. Put otherwise, being high fidelity is not just about exposing as many of the options of the cloud provider's API as possible, but also about exposing them at the same granularity as the cloud provider API.

If we write our managed resources such that, for example, you can only create a Virtual Network Rule as part of creating an Azure SQL Server (i.e. they're the same resource at the Crossplane level) we're in the game of second guessing and altering the granularity of the underlying APIs we represent. We're making assumptions about how our users will want to use the cloud provider that could potentially come back to bite us later when some user wants to be able to model just virtual network rules, or just SQL servers, not the two combined.

I feel it's quite important that the lowest layer of Crossplane (managed resources) are as high a fidelity representation of the cloud provider API both in functionality and granularity as is reasonably possible in a Kubernetes based declarative system. Doing so gives us a platform of composable primitives upon which we can build more opinionated concepts like "SQL server with virtual network rules" or "private S3 bucket with IAM user" without eliminating Crossplane as an option for folks who don't agree with those opinions (e.g. someone who wants just an SQL server with no virtual network rules, or just a virtual network rule applied to an SQL server Crossplane does not manage).

**Comment by negz** [comment]
The design changed a little as I wrote up a design for this, resulting in https://github.com/crossplaneio/crossplane/pull/1094.

**Comment by negz** [comment]
It seems unlikely we'll go with the specific direction proposed by this issue, but the overall problem remains. I've raised https://github.com/crossplaneio/crossplane/issues/1105 which focuses on the _problem we want to solve_, and discusses several of the solutions we've discussed without necessarily recommending one.
